// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreateCompanyProfileDto = {
    /**
     * Legal name of the company
     */
    legalName: string;
    /**
     * Company industry sector
     */
    industry?: 'AEROSPACE' | 'AGRICULTURE' | 'AUTOMOTIVE' | 'BANKING_INSURANCE' | 'CONSTRUCTION' | 'EDUCATION' | 'ENERGY' | 'HEALTHCARE' | 'HOSPITALITY' | 'IT_SERVICES' | 'LUXURY' | 'MANUFACTURING' | 'MEDIA_ENTERTAINMENT' | 'RETAIL' | 'PUBLIC_SECTOR' | 'TRANSPORT_LOGISTICS';
    /**
     * Company description
     */
    description?: {
        [key: string]: unknown;
    };
    /**
     * 14-digit SIRET number
     */
    siret?: {
        [key: string]: unknown;
    };
};

export type RegisterCompanyDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
    /**
     * Company profile details
     */
    profile: CreateCompanyProfileDto;
};

export type CreateStudentProfileDto = {
    /**
     * Student first name
     */
    firstName: string;
    /**
     * Student last name
     */
    lastName: string;
    /**
     * Name of the school
     */
    school?: {
        [key: string]: unknown;
    };
    /**
     * Name of the degree
     */
    degreeName?: {
        [key: string]: unknown;
    };
    /**
     * Start year of studies
     */
    startYear?: {
        [key: string]: unknown;
    };
    /**
     * Expected end year
     */
    endYear?: {
        [key: string]: unknown;
    };
    /**
     * Current study level
     */
    currentLevel?: 'BAC_PLUS_2' | 'BAC_PLUS_3' | 'BAC_PLUS_4' | 'BAC_PLUS_5' | 'BAC_PLUS_6' | 'DOCTORATE';
    /**
     * Target study level
     */
    targetLevel?: 'BAC_PLUS_2' | 'BAC_PLUS_3' | 'BAC_PLUS_4' | 'BAC_PLUS_5' | 'BAC_PLUS_6' | 'DOCTORATE';
    /**
     * List of past degrees
     */
    pastDegrees?: {
        [key: string]: unknown;
    };
    /**
     * List of technical skills
     */
    skills?: {
        [key: string]: unknown;
    };
    /**
     * Main field of study
     */
    fieldOfStudy?: 'ADMINISTRATION' | 'ARTS_DESIGN' | 'BUSINESS_MANAGEMENT' | 'COMMUNICATION' | 'COMPUTER_SCIENCE' | 'DATA_ANALYTICS' | 'ENGINEERING' | 'FINANCE_ACCOUNTING' | 'HUMAN_RESOURCES' | 'LAW' | 'MARKETING' | 'SALES';
    /**
     * URL to the CV
     */
    cvUrl?: {
        [key: string]: unknown;
    };
    /**
     * Contact phone number
     */
    contactPhoneNumber?: {
        [key: string]: unknown;
    };
    /**
     * Contact email address
     */
    contactEmail?: {
        [key: string]: unknown;
    };
};

export type RegisterStudentDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
    /**
     * Student profile details
     */
    profile: CreateStudentProfileDto;
};

export type LoginDto = {
    [key: string]: unknown;
};

export type RegisterDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type UpdateCompanyProfileDto = {
    /**
     * Legal name of the company
     */
    legalName?: string;
    /**
     * Company industry sector
     */
    industry?: 'AEROSPACE' | 'AGRICULTURE' | 'AUTOMOTIVE' | 'BANKING_INSURANCE' | 'CONSTRUCTION' | 'EDUCATION' | 'ENERGY' | 'HEALTHCARE' | 'HOSPITALITY' | 'IT_SERVICES' | 'LUXURY' | 'MANUFACTURING' | 'MEDIA_ENTERTAINMENT' | 'RETAIL' | 'PUBLIC_SECTOR' | 'TRANSPORT_LOGISTICS';
    /**
     * Company description
     */
    description?: string;
    /**
     * 14-digit SIRET number
     */
    siret?: string;
};

export type CreateOfferApplicationDto = {
    /**
     * ID of the student
     */
    studentId: number;
    /**
     * Cover letter or short pitch
     */
    description?: string;
    /**
     * URL to the student CV
     */
    cvUrl: string;
};

export type CreateOfferDto = {
    /**
     * Title of the job offer
     */
    title: string;
    /**
     * Detailed job description
     */
    description: string;
    /**
     * Location of the job
     */
    location: string;
    /**
     * Monthly salary in EUR
     */
    salary?: {
        [key: string]: unknown;
    };
    /**
     * Required field of study for the offer
     */
    fieldOfStudy: 'ADMINISTRATION' | 'ARTS_DESIGN' | 'BUSINESS_MANAGEMENT' | 'COMMUNICATION' | 'COMPUTER_SCIENCE' | 'DATA_ANALYTICS' | 'ENGINEERING' | 'FINANCE_ACCOUNTING' | 'HUMAN_RESOURCES' | 'LAW' | 'MARKETING' | 'SALES';
    /**
     * Status of the offer. Defaults to DRAFT
     */
    status?: 'DRAFT' | 'PUBLISHED';
};

export type AccountControllerRegisterCompanyData = {
    body: RegisterCompanyDto;
    path?: never;
    query?: never;
    url: '/auth/register/company';
};

export type AccountControllerRegisterCompanyResponses = {
    201: unknown;
};

export type AccountControllerRegisterStudentData = {
    body: RegisterStudentDto;
    path?: never;
    query?: never;
    url: '/auth/register/student';
};

export type AccountControllerRegisterStudentResponses = {
    201: unknown;
};

export type AccountControllerDeleteAccountData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}/account';
};

export type AccountControllerDeleteAccountResponses = {
    200: unknown;
};

export type AccountControllerGetAccountData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}/account';
};

export type AccountControllerGetAccountResponses = {
    200: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    201: unknown;
};

export type AuthControllerRequestPasswordRestData = {
    body?: never;
    path?: never;
    query: {
        email: string;
    };
    url: '/auth/request-password-reset';
};

export type AuthControllerRequestPasswordRestResponses = {
    200: unknown;
};

export type AuthControllerResetPasswordData = {
    body: RegisterDto;
    path?: never;
    query: {
        otp: string;
    };
    url: '/auth/reset-password';
};

export type AuthControllerResetPasswordResponses = {
    201: unknown;
};

export type CompanyControllerGetCompanyProfileData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/companies/{id}/profile';
};

export type CompanyControllerGetCompanyProfileResponses = {
    200: unknown;
};

export type CompanyControllerUpdateCompanyProfileData = {
    body: UpdateCompanyProfileDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/companies/{id}/profile';
};

export type CompanyControllerUpdateCompanyProfileResponses = {
    200: unknown;
};

export type StudentControllerGetStudentProfileData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/students/{userId}/profile';
};

export type StudentControllerGetStudentProfileResponses = {
    200: unknown;
};

export type StudentControllerUpdateCompanyProfileData = {
    body: UpdateCompanyProfileDto;
    path: {
        userId: number;
    };
    query?: never;
    url: '/students/{userId}/profile';
};

export type StudentControllerUpdateCompanyProfileResponses = {
    200: unknown;
};

export type OfferApplicationControllerApplyData = {
    body: CreateOfferApplicationDto;
    path: {
        offerId: number;
    };
    query?: never;
    url: '/offers/{offerId}/apply';
};

export type OfferApplicationControllerApplyResponses = {
    201: unknown;
};

export type OfferApplicationControllerCancelApplicationData = {
    body?: never;
    path: {
        applicationId: number;
    };
    query?: never;
    url: '/applications/{applicationId}';
};

export type OfferApplicationControllerCancelApplicationResponses = {
    200: unknown;
};

export type OfferApplicationControllerGetApplicationsByStudentIdData = {
    body?: never;
    path: {
        studentId: number;
    };
    query?: never;
    url: '/students/{studentId}/applications';
};

export type OfferApplicationControllerGetApplicationsByStudentIdResponses = {
    200: unknown;
};

export type OfferApplicationControllerGetApplicationByOfferIdData = {
    body?: never;
    path: {
        offerId: number;
    };
    query?: never;
    url: '/offers/{offerId}/applications';
};

export type OfferApplicationControllerGetApplicationByOfferIdResponses = {
    200: unknown;
};

export type OfferControllerGetOffersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/offers';
};

export type OfferControllerGetOffersResponses = {
    200: unknown;
};

export type OfferControllerDeleteOfferData = {
    body?: never;
    path: {
        offerId: number;
    };
    query?: never;
    url: '/offers/{offerId}';
};

export type OfferControllerDeleteOfferResponses = {
    200: unknown;
};

export type OfferControllerGetOfferData = {
    body?: never;
    path: {
        offerId: number;
    };
    query?: never;
    url: '/offers/{offerId}';
};

export type OfferControllerGetOfferResponses = {
    200: unknown;
};

export type OfferControllerGetOffersByCompanyIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/companies/{id}/offers';
};

export type OfferControllerGetOffersByCompanyIdResponses = {
    200: unknown;
};

export type OfferControllerCreateOfferData = {
    body: CreateOfferDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/companies/{id}/offers';
};

export type OfferControllerCreateOfferResponses = {
    201: unknown;
};

export type OfferControllerUpdateOfferData = {
    body: CreateOfferDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/offers/{id}';
};

export type OfferControllerUpdateOfferResponses = {
    200: unknown;
};

export type OfferControllerPublishOfferData = {
    body?: never;
    path: {
        offerId: number;
    };
    query?: never;
    url: '/offers/{offerId}/publish';
};

export type OfferControllerPublishOfferResponses = {
    200: unknown;
};

export type OfferControllerCloseOfferData = {
    body?: never;
    path: {
        offerId: number;
    };
    query?: never;
    url: '/offers/{offerId}/close';
};

export type OfferControllerCloseOfferResponses = {
    200: unknown;
};

export type TestControllerHelloWorldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test';
};

export type TestControllerHelloWorldResponses = {
    200: unknown;
};

export type TestControllerTestAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test/auth';
};

export type TestControllerTestAuthResponses = {
    200: unknown;
};

export type TestControllerTestAdminRoleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test/admin';
};

export type TestControllerTestAdminRoleResponses = {
    200: unknown;
};

export type TestControllerTestStudentRoleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test/student';
};

export type TestControllerTestStudentRoleResponses = {
    200: unknown;
};

export type TestControllerTestCompanyRoleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test/company';
};

export type TestControllerTestCompanyRoleResponses = {
    200: unknown;
};

export type TestControllerGetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test/user';
};

export type TestControllerGetUserResponses = {
    200: unknown;
};
